### ISSUE TITLE
Doubling image on header

### ISSUE THREAD

**Issue by GHEEV** [carlonzo/StikkyHeader#28]
My header is doubling the size. But one is my image header and other is a blank image. How can I solve that?
![screenshot_2015-03-08-18-01-08](https://cloud.githubusercontent.com/assets/6901088/6547678/b63b9aaa-c5bd-11e4-9630-991b97625044.png)
![screenshot_2015-03-08-18-01-00](https://cloud.githubusercontent.com/assets/6901088/6547680/bfaae168-c5bd-11e4-8306-9700f44f6b93.png)

code XML: 

       <FrameLayout
            android:id="@+id/header"
            android:layout_width="match_parent"
            android:layout_height="180dp"
            >

            <ImageView
                android:id="@+id/header_image"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:scaleType="centerCrop"
                android:src="@drawable/alimentacao" />
        </FrameLayout>

code Android:

        StikkyHeaderBuilder.stickTo(list)
                    .setHeader(R.id.header, parent)
                    .minHeightHeaderRes(R.dimen.min_height_header)
                    .animator(new ParallaxStikkyAnimator())
                    .build();

**Comment by carlonzo** [comment]
would you mind to send me the source code? here it looks fine..

**Comment by GHEEV** [comment]
My code is very big. If you need, I can send you the code. I'm trying to do an app test, But in my code, the only thing different is a SlideUpPanel library I'm using too.. Is that a problem?

**Comment by GHEEV** [comment]
I found the issue. I'm using a Relative Layout as a parent, and not a Frame Layout. Changing that solve the issue. Thanks for your time!

**Comment by carlonzo** [comment]
happy you solved the problem. please let me see the result when you finish the app :)

**Comment by GHEEV** [comment]
Of course, I'll! :)

**Comment by carlonzo** [comment]
for your information (if you havent seen it): few days ago I've published the lib on maven, so its much easier to include it to your project

**Comment by GHEEV** [comment]
Yes! I'm using by
maven {
            url "https://jitpack.io"
        }
and
compile 'com.github.carlonzo:StikkyHeader:cbb0622a7b'

from Android-Arsenal. Is it updated?

**Comment by carlonzo** [comment]
I didnt know about it. its not my repo, but it should work anyway. if you want to use mine, you can find everything on the main page

**Comment by GHEEV** [comment]
Really? I'll update my maven so, I'll use yours. I almost forget, really amazing lib/work, man! :D

**Comment by carlonzo** [comment]
:) thanks

Il giorno dom 8 mar 2015 alle ore 22:03 Guilherme Henrique <
notifications@github.com> ha scritto:

**Comment by GHEEV** [comment]
Hey, there is any way to do something like the PlayStore toolbar? With fade color above image?

**Comment by carlonzo** [comment]
You could create an Animator an fade the image to a color, a set the
minHeight of the StikkyHeader to the height of the toolbar (transparent).

it should work :)

Il giorno mar 31 mar 2015 alle ore 03:02 Guilherme Henrique <
notifications@github.com> ha scritto:
