### ISSUE TITLE
ScrollListener

### ISSUE THREAD

**Issue by ImpYoo** [carlonzo/StikkyHeader#44]
after sticking the recyclerview to the StickyHeaderBuilder I don't get any response from the ScrollListener.

**Comment by carlonzo** [comment]
I've already solved this problem here: https://github.com/carlonzo/StikkyHeader/pull/40
I will release soon the new version on maven. The new RecyclerView introduced a new api "addOnScrollListener" so we can attach multiple ScrollListener.
