### ISSUE TITLE
visual bug after items on adapter change

### ISSUE THREAD

**Issue by rehacktive** [carlonzo/StikkyHeader#45]
Hi,
I've correctly added the header to a recycler view and everything works fine - also with animation.
But, after I go to another activity, make an action that modifies the number of items on the recycler adapter (add one item at a specific position) and go back, the content is reloaded, showing the new item, but it appears a blank area at top.

Is there something I have to do?
I've tried to scroll to the top (even if it's not what I want), but it's still broken.

onResume I just reload the content, than set the new content on the adapter and call notifyDataSetChanged().

Any help will be appreciated.

**Comment by carlonzo** [comment]
Hi,
I think that your problem is related to this issue here: https://github.com/carlonzo/StikkyHeader/issues/36

I am working on a solution. sorry about that.

**Comment by rehacktive** [comment]
thanks. Apparently it works fine without the animation - I just tried.
I can go without it (even if it was very cool!) but maybe this can help you to understand what to fix.

**Comment by carlonzo** [comment]
Thanks. I'vent noticed that :/ weird.

**Comment by rehacktive** [comment]
(no, it happens sometimes even without animation...)

**Comment by carlonzo** [comment]
mmm ok! I've a working solution but the animation is broken. I "just" need to understand how to fix it

**Comment by carlonzo** [comment]
we can continue the discussion on the other issue
