### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by dorinsimina** [carlonzo/StikkyHeader#48]
Does anyone know how to fix the following error:
Error:Module version com.github.carlonzo.stikkyheader:core:0.0.2-SNAPSHOT depends on libraries but is not a library itself

Thanks in advance,
Dorin

**Comment by al11al** [comment]
I agree also I even can't find  carlonzo.stikkyheader in maven central.

**Comment by al11al** [comment]
Oh sorry. Just required to add this and read  READ.ME as well)
repositories {
  maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

**Comment by carlonzo** [comment]
@dorinsimina try to update to the version 0.0.3 and let me know if it happens.
