### ISSUE TITLE
Access ItemDecoration

### ISSUE THREAD

**Issue by pawegio** [carlonzo/StikkyHeader#53]
I would like to remove item decoration created by StikkyHeader so I need to access it by reference.

EDIT: I created a pull request for that https://github.com/carlonzo/StikkyHeader/pull/54

**Comment by carlonzo** [comment]
Whats the point to remove the item decoration?

**Comment by pawegio** [comment]
I needed to remove header when SearchView expands.

**Comment by carlonzo** [comment]
I would not give access to the itemDecorator. What about reducing the size of the header to 0? yeah, its not the finest solution but after https://github.com/carlonzo/StikkyHeader/pull/60 the StikkyHeader listen to the changing in the sizes of the header. let me know your thought
