### ISSUE TITLE
 header's height shoud be changed when header add some other view,but not,why?

### ISSUE THREAD

**Issue by qingfengmy** [carlonzo/StikkyHeader#56]
myheader is a linearlayout,and it add a new view after i stickTo listview, then the header's height shoud be changed, but it does't.

**Comment by carlonzo** [comment]
thats a bug. the library do not update the height of the listview's header. I will fix it

**Comment by carlonzo** [comment]
please leave it open. it has not been fixed.

**Comment by EmpiezaAProgramar** [comment]
I hope you can fix it. I like your library and you've got a lot of forks and stars, but this bug is serius. One more time, I hope you can fix it and thanks for your work :D.

**Comment by carlonzo** [comment]
now this is the next on my TODO

**Comment by carlonzo** [comment]
now should be fixed with this https://github.com/carlonzo/StikkyHeader/pull/60. please try it and let me know if this works now.

**Comment by qingfengmy** [comment]
yes, the bug is fixed. but the new  added view can't be scrolled. the header's scroll  area is like before.but the new view should be scrolled.

**Comment by carlonzo** [comment]
to be fixed...

Il giorno ven 18 set 2015 alle ore 09:15 qingfengmy <
notifications@github.com> ha scritto:
