### ISSUE TITLE
Notify when animation completes

### ISSUE THREAD

**Issue by virenpurohit** [carlonzo/StikkyHeader#67]
Hello,
Thanx for your fabulous library.

I am using it in one of my projects. Is there any way to get notified when header animation get completed.

I mean we pass minimum height to header and scrolling gets stopped on reaching that height so is there any kinda method is there through which we could get that animation completed because I want that.

**Comment by carlonzo** [comment]
Hi Thanks,
you can extend the `onScroll` method of the `Animator` and get the scrolled value calling `getBoundedTranslatedRatio`. when the ratio is `1.0f`, the header is full scrolled.
